FROM openjdk:17-oracle
EXPOSE 8080
ADD /target/adopet-0.0.1-SNAPSHOT.jar adopet.jar
ENTRYPOINT ["java","-jar","adopet.jar"]
#
#FROM adoptopenjdk/openjdk11
#EXPOSE 8080
#ADD /target/treinamentoKotlin-0.0.1-SNAPSHOT.jar treinametoAlura.jar
#ENTRYPOINT ["java", "jar", "treinametoAlura.jar"]